platform :ios, '8.0'
use_frameworks!

target "kaisafax" do
    pod 'LogglyLogger-CocoaLumberjack', '~> 2.3.2' #基于CocoaLumberjack的日志工具，暂时不要使用高于2.2.0版本以上的CocoaLumberjack
    pod 'CocoaLumberjack', '~> 2.2.0'  #颜色日志, 需要xcode安装插件配置使用, 可以使用日志有多种颜色, 方便查看
    pod 'MJRefresh', '~> 3.1.12' #tableview 中下拉上接更新
    pod 'AFNetworking', '~> 3.0.4' #网络请求
    #pod 'AFDownloadRequestOperation', '~> 2.0.1' #基于AFN(2.0)的下载扩展工具
    pod 'SDWebImage', '~> 3.7.4' #网络图片缓存库
    pod 'UITableView+FDTemplateLayoutCell', '~> 1.4' #动态计算tableviewcell的高度
    pod 'JSONKit-NoWarning', '~> 1.2' #json解析库
    #pod 'Mantle', '~> 2.0.6' #将 JSON 数据模型化为 Model 对象
    pod 'YYModel', '~> 1.0.4' #YYKit库 将 JSON 数据模型化为 Model 对象
    pod 'DACircularProgress', '~> 2.3.1' #投资列表中的圆形进度条
    pod 'M13Checkbox', '~> 1.2.0' # 注册选择注册协议可以使用
    pod 'MBProgressHUD', '~> 0.9.2' #网络请求阻塞指示器
    pod 'Toast', '~> 3.0' #弹出提示信息
    pod 'ReactiveCocoa', '~> 4.2.2' # 整个APP 可使用,响应式
    #pod 'ReactiveViewModel', '~> 0.3' # 整个APP 可使用,基于ReactiveCocoa响应式的view model
    pod 'MZTimerLabel', '~> 0.5.4' #投资列表中的倒计时
    pod 'WMPageController', '1.9.6' # 使用场景 -> 可提奖励, 我的红包等有SegmentedControl的界面
    pod 'DZNEmptyDataSet', '~> 1.7.3' #tableview数据为空的时候
    #pod 'StaticDataTableViewController', '~> 2.0.5' #动态删除静态cell, 账户安全, 可以动态的删除static tableview cell, 如不是业主用户, 可以删除
    pod 'XWebView', '~> 0.10.0' #webviewcontroller使用 JS 交互
    pod 'NUI', '~> 0.5.5' #控件使用 CSS 自定义样式
    pod 'LTNavigationBar', '~> 2.1.2'  #需要动态透明NavigationBar使用, 如首页
    #pod 'SCLAlertView-Objective-C', '~> 1.0.3' #自定义的alertview
    pod 'LGAlertView', '~> 2.2.0' #自定义的alertview
    pod 'FMDB', '~> 2.6.2' #sqlite数据库多线程安全操作库
    pod 'Masonry', '~> 1.0.1' #界面相对布局框架,某种程度上替换Autolayout
    pod 'FDStackView', '~> 1.0' #兼容ios9以下的UIStackView库
    #pod 'MJExtension', '~> 3.0.13' #将 JSON 数据,字典，数组等模型化为 Model 对象
    pod 'BEMCheckBox', '~> 1.2.1' #check box按钮
    pod 'YYText', '~> 1.0.7' #YYKit库 label textview
    pod 'UMengAnalytics', '~> 4.2.4' #友盟统计标准SDK，含IDFA
    pod 'ZXingObjC', '~> 3.0' #二维码
    pod 'IQKeyboardManager', '~> 4.0.5' #键盘的处理工具，防止遮罩
    #pod 'KMCGeigerCounter', '~> 0.2.2' #测试 APP 流畅度, 发正式包要去掉
    pod 'SDCycleScrollView', '~> 1.65' #轮播控件
    #pod 'UICKeyChainStore', '~> 2.1.0' #keychain的API封装
    #pod 'SAMKeychain', '~> 1.5.2' #keychain的API封装
    pod 'AMPopTip', '~> 1.3.0' #浮动提示框
    #pod 'EasyTableView', '~> 2.0.3' #可以横向滚动的TableView
    #pod 'iOS-Echarts', '~> 1.4.3' #图形视图，饼状图，k线图
    pod 'NSHash', '~> 1.0.2'  #加密 MD5 SHA1 SHA256
    #pod 'GZIP', '~> 1.1.1'  #GZIP压缩
    #pod 'NJKWebViewProgress', '~> 0.2.3'  #a progress interface library for UIWebView
    pod 'Aspects', '~> 1.4.1'  #hook
    pod 'M13OrderedDictionary', '~> 1.1.0' #有序字典
    #pod 'OrderedDictionary', '~> 1.4' #有序字典 OrderedDictionary requires ARC；
    #pod 'PLCrashReporter', '~> 1.2.0' #crash上报工具库，给PerformanceMonitor卡顿监测使用
    pod 'WechatOpenSDK', '~> 1.7.7' #微信开放平台移动API
    pod 'WeiboSDK', :git => 'https://github.com/sinaweibosdk/weibo_ios_sdk.git' #微博开放平台API 3.2
    
    #设置swift为编译版本为2.3
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '2.3'
            end
        end
    end
end
